---
apiVersion: v1
kind: Namespace
metadata:
  name: qrscanner

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qrscanner-config
  namespace: qrscanner
data:
  REACT_APP_API_URL: "http://51.83.161.218:9944/api"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: qrscanner
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: qrscanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pakubjajor/qrscanner-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: qrscanner-config
              key: REACT_APP_API_URL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
